version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build
  post_build:
     commands:
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes